### ISSUE TITLE
Dynamic supervisor not found.

### ISSUE THREAD

**Issue by CrowdHailer** [peburrows/river#6]
Howdy.

First up excited that someone has started working on this project. I am having a go at implementing a HTTP/2.0 server and want to use river for testing. unfortunetly I get this error.

```
== Compilation error on file lib/river/stream_supervisor.ex ==
** (CompileError) lib/river/stream_supervisor.ex:3: module Experimental.DynamicSupervisor is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/river/stream_supervisor.ex:3: River.StreamSupervisor (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Am using elixir 1.4.5

**Comment by peburrows** [comment]
Ah, yeah, that's because I was originally using the `Experimental.DynamicaSupervisor` module from the early `GenStage` work, which has since been rolled into the standard lib (and had the `Experimental` namespace removed).

I'll need to update some dependencies and do a few other things to get stuff working going forward, but for now, I think you should be able to fix the issue by pinning to version `0.5` of the `:gen_stage` dependency:

```elixir
{:gen_stage, "0.5"}
```

**Comment by CrowdHailer** [comment]
Hi, I'm unlikely to peg `gen_stage` that far back as I'm possibly using `GenStage` server side and would want to work with the most recent. For the moment I have fallen back to directly calling `:gen_tcp` directly in my tests. Hopefully I will be able to use a client for a more full suite of tests later on.

**Comment by ktimothy** [comment]
Same problem here =(

**Comment by peburrows** [comment]
This should be fixed with v0.0.5, which has just been pushed to hex.

**Comment by CrowdHailer** [comment]
thanks

@peburrows Can I ask you what are you using river for at the moment?

**Comment by peburrows** [comment]
@CrowdHailer currently, I'm using River in very specific situations where I know the only endpoints I'm hitting support http/2. River doesn't currently have http/1.x support, so until it does, it can't really be used as a more general http client. There's also still plenty of the http/2 spec left to implement, so there are edge cases where River will currently fail.

All that being said, my near-term goal is to use River in all my GCP libraries ([goth](https://github.com/peburrows/goth), [diplomat](https://github.com/peburrows/diplomat), and [kane](https://github.com/peburrows/kane)), and eventually build a grpc library that uses River as well.

**Comment by CrowdHailer** [comment]
Interesting. Do you plan to implement only the client side of the gRPC?

**Comment by peburrows** [comment]
Right now, I only plan on implementing the client side, but that might change as I get into the project a bit more. At the very least, a gRPC client is a much higher priority for me personally than a gRPC server.
